vich_uploader:
    db_driver: orm
    mappings:
        sweatshirt_image:
            uri_prefix: /uploads/images/sweatshirts
            upload_destination: '%kernel.project_dir%/public/uploads/images/sweatshirts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer