vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        sweatshirts_images:
            uri_prefix: /uploads/images/sweatshirt
            upload_destination: '%kernel.project_dir%/public/uploads/images/sweatshirts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
